spring:

    datasource:
        hikari:
#            auto-commit: false
             minimum-idle: 3
             maximum-pool-size: 3
        type: com.zaxxer.hikari.HikariDataSource

        instance: sasdev3
        db: 10.134.112.3:5432

        url: jdbc:postgresql://${spring.datasource.db}/${spring.datasource.instance}
        username: csc
        password: ${spring.datasource.username}_${spring.datasource.instance}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL95Dialect
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
#            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: POS
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
            hibernate.proc.param_null_passing: true
